In [1]:
import numpy as np

Di NumPy, Anda dapat menggunakan indexing, slicing, dan iterasi untuk mengakses dan memanipulasi array secara efisien. Berikut adalah penjelasan singkat tentang masing-masing konsep:

# Indexing:
Dalam NumPy, indexing digunakan untuk mengakses elemen tertentu dalam array dengan mengacu pada posisi atau indeksnya. Anda dapat menggunakan indeks tunggal atau indeks multi-dimensi untuk mengakses elemen-elemen tersebut. Misalnya:

In [7]:
arr = np.array([10,20,30,40,50])
print(arr[0]) #angka pertama
print(arr[0:2]) #angka ke 30 not include
print(arr[-1]) #angka terakhir 

10
[10 20]
50


In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,2]) #baris ke 1 dan kolom ke 2

[[1 2 3]
 [4 5 6]]
6


# Slicing:
Slicing digunakan untuk mengambil subarray (potongan) dari array asli dengan menentukan rentang indeks tertentu. Anda dapat memotong array dalam satu dimensi atau multi-dimensi. Misalnya:

In [36]:
arr3 = np.array([10,20,30,40,50])
print(arr3[1:4])

[20 30 40]


In [15]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr4[1:3,0:2])
print("=========================")
print(arr4[-1,0:2])
print("=========================")
print(arr4[0:2,2])
print("=========================")
print(arr4[:,1:3])

[[4 5]
 [7 8]]
[7 8]
[3 6]
[[2 3]
 [5 6]
 [8 9]]


# Stacking
Dalam NumPy, Anda dapat menggunakan fungsi numpy.stack() untuk melakukan stacking (penggabungan) array secara horizontal atau vertical. Stacking memungkinkan Anda menggabungkan beberapa array menjadi satu array yang baru.

Berikut adalah penjelasan singkat tentang stacking dalam NumPy:

# 1.Horizontal Stacking

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
print(arr3)

[1 2 3 4 5 6]


contoh 2:

In [22]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [26]:
y=np.hstack((a,b))
print(y)

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


# 2.Vertical Stacking
Vertical stacking menggabungkan array secara vertikal atau sepanjang sumbu baris. Anda dapat menggunakan fungsi numpy.vstack() atau numpy.concatenate() dengan parameter axis=0 untuk melakukan vertical stacking. Contoh:

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.vstack((arr1, arr2))
# atau arr3 = np.concatenate((arr1, arr2), axis=1)
print(arr3)

[[1 2 3]
 [4 5 6]]


# 3.Depth Stacking
Depth stacking menggabungkan array secara sepanjang sumbu kedalaman atau sumbu baru. Anda dapat menggunakan fungsi numpy.dstack() untuk melakukan depth stacking. Contoh:

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.dstack((arr1, arr2))
print(arr3)

[[[1 4]
  [2 5]
  [3 6]]]


# Split
Dalam NumPy, Anda dapat menggunakan fungsi numpy.split() untuk membagi (split) array menjadi beberapa subarray berdasarkan indeks atau posisi yang ditentukan. Fungsi ini memungkinkan Anda membagi array menjadi bagian yang lebih kecil.

Berikut adalah penjelasan singkat tentang fungsi split dalam NumPy:



# 1.Splitting Secara Horizontal
Splitting secara horizontal membagi array menjadi subarray yang memiliki ukuran yang sama sepanjang sumbu kolom (axis 1). Anda dapat menggunakan fungsi numpy.hsplit() untuk melakukan splitting horizontal. Contoh:

In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
subarrays = np.hsplit(arr, 2)
print(subarrays)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# 2.Splitting Secara Vertical
Splitting secara vertical membagi array menjadi subarray yang memiliki ukuran yang sama sepanjang sumbu baris (axis 0). Anda dapat menggunakan fungsi numpy.vsplit() untuk melakukan splitting vertical. Contoh:

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subarrays = np.vsplit(arr, 3)
print(subarrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


# 3.Splitting Secara Custom
Anda juga dapat melakukan splitting dengan mengatur posisi pemotongan secara manual menggunakan indeks yang ditentukan. Anda dapat menggunakan fungsi numpy.split() untuk melakukan splitting dengan indeks yang ditentukan. Contoh:

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])
subarrays = np.split(arr, [2, 4])
print(subarrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


# indexing with boolean array

Dalam NumPy, Anda dapat menggunakan indeks boolean untuk mengindeks array dan memilih elemen-elemen yang sesuai dengan nilai True dalam boolean array. Ini disebut juga indexing dengan boolean array atau boolean indexing.

Berikut adalah penjelasan singkat tentang indexing dengan boolean array dalam NumPy:

# 1.Membuat Boolean Array:
Pertama, Anda perlu membuat sebuah boolean array dengan kondisi yang ingin Anda gunakan sebagai pemilihan elemen. Misalnya:

In [33]:
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2
print(bool_arr)

[False False  True  True  True]


# 2.Menggunakan Boolean Array untuk Indexing:
Setelah Anda memiliki boolean array, Anda dapat menggunakannya sebagai indeks untuk memilih elemen-elemen yang sesuai dengan nilai True dalam boolean array tersebut. Contoh:

In [34]:
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2
new_arr = arr[bool_arr]
print(new_arr)

[3 4 5]


Anda juga dapat melakukan indexing dengan boolean array langsung tanpa variabel tambahan:

In [35]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[arr > 2]
print(new_arr)

[3 4 5]
