# Load in Numpy(remember to pip install numpy first)

NumPy (Numerical Python) adalah sebuah library atau pustaka Python yang digunakan untuk melakukan operasi numerik pada array multidimensi. NumPy menyediakan struktur data yang efisien, seperti array N-dimensi (ndarray), yang memungkinkan Anda untuk melakukan operasi matematika dan logika pada array dengan mudah.

NumPy merupakan salah satu pustaka yang paling penting dalam ekosistem ilmu data Python karena menyediakan banyak fungsi dan metode untuk memanipulasi array dan melakukan komputasi numerik. Pustaka ini sangat efisien dalam melakukan operasi pada array besar, sehingga sering digunakan dalam analisis data, komputasi ilmiah, dan pembelajaran mesin.

Berikut adalah beberapa fitur utama dari NumPy:

1. Array N-dimensi: NumPy menyediakan objek ndarray yang merupakan array N-dimensi. Anda dapat membuat array dengan berbagai dimensi, seperti vektor (1D), matriks (2D), atau array dengan dimensi yang lebih tinggi.

2. Operasi matematika: NumPy menyediakan berbagai fungsi matematika yang dapat diterapkan pada array, seperti penjumlahan, pengurangan, perkalian, pembagian, eksponen, dan fungsi trigonometri. Fungsi-fungsi ini dapat diterapkan pada seluruh array atau elemen per elemen.

3. Broadcasting: NumPy memungkinkan broadcasting, yaitu mengubah bentuk array secara otomatis untuk memungkinkan operasi matematika antara array dengan bentuk yang berbeda. Hal ini memungkinkan Anda untuk melakukan operasi pada array dengan ukuran yang berbeda tanpa perlu mengulangi atau memperluas array.

4. Operasi statistik: NumPy menyediakan fungsi untuk menghitung statistik pada array, seperti mean, median, standar deviasi, variansi, dan lainnya.

5. Pengindeksan dan pemotongan array: Anda dapat mengakses dan memanipulasi elemen-elemen dalam array dengan menggunakan indeks dan slicing. NumPy mendukung pengindeksan berbasis integer, boolean, atau kondisi logika.

NumPy merupakan bagian dari ekosistem ilmu data Python yang juga termasuk pustaka-pustaka seperti Pandas, Matplotlib, dan Scikit-learn. Dengan menggunakan NumPy, Anda dapat melakukan operasi numerik dengan cepat dan efisien pada array multidimensi dalam Python.

#pip install numpy

In [49]:
import numpy as np

# The Basics Array
Dalam NumPy, dimensi mengacu pada jumlah sumbu yang ada dalam array. NumPy mendukung array dengan dimensi yang bervariasi, mulai dari array satu dimensi hingga array multi dimensi.

Anda dapat menggunakan atribut ndim untuk mendapatkan jumlah dimensi dari suatu array NumPy. Berikut ini adalah contoh penggunaannya:

Create One dimensional array :

In [105]:
a = np.array([1,2,3])
print(a)

[1 2 3]


# Get Dimension (ndim)

In [50]:
a.ndim

1

Create Two dimensional array :

In [8]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
b.ndim

2

# Get Item Size Property (itemsize)
Properti itemsize digunakan dalam NumPy untuk mengambil ukuran dalam byte dari setiap elemen dalam array. Properti ini sangat berguna ketika kita ingin mengetahui berapa banyak ruang yang ditempati oleh setiap elemen dalam array.

Berikut ini adalah contoh penggunaan properti itemsize:

In [31]:
a.itemsize

4

Dalam contoh ini, kita membuat array a dengan tipe data integer 32-bit. Kemudian, kita menggunakan properti itemsize pada array a untuk mendapatkan ukuran dalam byte dari setiap elemen dalam array. Hasilnya adalah 4, yang menunjukkan bahwa setiap elemen dalam array a membutuhkan 4 byte ruang dalam memori.

# Get Data Type Property (dtype)
Properti dtype digunakan dalam NumPy untuk mendapatkan tipe data dari elemen-elemen dalam array. Properti ini berguna untuk mengetahui tipe data yang digunakan dalam array, seperti bilangan bulat, bilangan desimal, string, dll.

Berikut ini adalah contoh penggunaan properti dtype:

In [28]:
a.dtype

dtype('int32')

In [121]:
b = np.array([[1,2],[3,4],[5,6]])
print(b)
b.itemsize

[[1 2]
 [3 4]
 [5 6]]


4

In [112]:
b.dtype

dtype('int32')

In [106]:
c = np.array(['a', 'b', 'c'])
print(c)

['a' 'b' 'c']


In [107]:
c.dtype

dtype('<U1')

# Change Data Type Of Element

In [109]:
b = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
b.dtype

dtype('float64')

Untuk mengubah tipe data array NumPy, Anda dapat menggunakan metode astype() yang memungkinkan Anda untuk mengonversi array ke tipe data lain. Metode ini mengembalikan salinan array dengan tipe data yang diubah.

Berikut adalah contoh penggunaan metode astype() untuk mengubah tipe data array:

In [117]:
b = np.array([[1,2],[3,4],[5,6]])
bint = b.astype(float)
bint.dtype

dtype('float64')

In [120]:
print(b)
bint.itemsize

[[1 2]
 [3 4]
 [5 6]]


8

catatan: maka data yang diubah akan bertype data float64 dan itemsize 8

# Get Size Property (size) 
Properti size digunakan dalam NumPy untuk mengambil jumlah total elemen dalam array. Properti ini memberikan informasi tentang ukuran keseluruhan dari array.

Berikut ini adalah contoh penggunaan properti size:

In [123]:
print(c)
c.size

['a' 'b' 'c']


3

# Get Shape Property (shape) 
Properti shape digunakan dalam NumPy untuk mengambil tuple yang menunjukkan dimensi dari array. Properti ini memberikan informasi tentang ukuran setiap dimensi dalam array.

Berikut ini adalah contoh penggunaan properti shape:

In [42]:
b.shape

(3, 2)

Array b memiliki dimensi (3, 2), yang menunjukkan bahwa itu adalah array dua dimensi dengan 3 baris dan 2 kolom.

# Zeros() Function
Fungsi zeros() dalam NumPy digunakan untuk membuat array berisi nol dengan ukuran dan tipe data yang ditentukan.

Berikut adalah contoh penggunaan zeros():

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Ones() Function
Anda ingin membuat array yang berisi satu dengan ukuran dan tipe data yang ditentukan, Anda dapat menggunakan fungsi ones().

Berikut adalah contoh penggunaan ones():

In [53]:

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Range() Function

Fungsi range() adalah fungsi bawaan dalam Python yang digunakan untuk menghasilkan urutan bilangan. Namun, dalam konteks NumPy, fungsi range() tidak ada. NumPy menyediakan fungsi lain yang mirip, yaitu arange().

Fungsi arange() dalam NumPy digunakan untuk menghasilkan urutan bilangan dalam array berdasarkan interval yang ditentukan.

In [4]:
i = range(5)
print(i)

range(0, 5)


In [57]:
i[0]

0

In [137]:
i[4]

4

Berikut adalah contoh penggunaan arange():

In [59]:
np.arange(1,5)

array([1, 2, 3, 4])

In [60]:
np.arange(1,5,2)

array([1, 3])

catatan : Start = 1 ,Stop = 5 , dan Interval = 2

Fungsi arange() juga dapat digunakan dengan parameter opsional dtype untuk menentukan tipe data array yang dihasilkan.

In [138]:
k = np.arange(0, 1, 0.1, dtype=float)
print(k)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# Linespace() Function
Fungsi linspace() dalam NumPy digunakan untuk menghasilkan urutan bilangan dalam array dengan jumlah titik yang ditentukan secara merata di antara dua nilai tertentu.

Berikut adalah contoh penggunaan linspace():

In [139]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [140]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [141]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


# Reshape() Function
Fungsi reshape() dalam NumPy digunakan untuk mengubah bentuk (shape) dari suatu array, yaitu mengatur ulang dimensi array tanpa mengubah data yang ada.

Berikut adalah contoh penggunaan reshape():

In [144]:
var = np.array([[1,2],[3,4],[5,6]])
print(var)

[[1 2]
 [3 4]
 [5 6]]


In [145]:
var.shape

(3, 2)

In [146]:
var.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

catatan : Mengubah Row dan Coloumn

# Ravel() Function
Fungsi ravel() dalam NumPy digunakan untuk mengubah array multidimensi menjadi array 1D. Fungsi ini menghasilkan tampilan yang "diratakan" dari array asli, yaitu membuat array baru yang berisi semua elemen array asli dalam urutan yang sama.

Berikut adalah contoh penggunaan ravel():

In [147]:
var.ravel()

array([1, 2, 3, 4, 5, 6])

In [148]:
print(var)

[[1 2]
 [3 4]
 [5 6]]


# Statistics

In [149]:
print(var)

[[1 2]
 [3 4]
 [5 6]]


Min() Function :  Menghitung nilai minimum dari array.

In [167]:
var.min()
print(np.min(var))

1


Max() Funtion : Menghitung nilai maksimum dari array.

In [168]:
var.max()

6

mean() Function : Menghitung nilai rata-rata dari array.

In [152]:
var.mean()

3.5

median() Function : Menghitung nilai median dari array.

In [156]:
me = np.array([2, 4, 6, 8, 10])
print(np.median(me))
print(np.median(var))

6.0
3.5


Sum() Function : Menghitung jumlah dari semua elemen dalam array.

In [169]:
var.sum()

21

In [159]:
print(var)

[[1 2]
 [3 4]
 [5 6]]


In [158]:
#catatan : Menghitung Jumlah Baris
var.sum(axis=0)

array([ 9, 12])

In [173]:
#catatan : Menghitung Jumlah Kolom
var.sum(axis=1)

array([ 3,  7, 11])

Var() Function : Menghitung variansi dari array.

In [172]:
print(np.var(var))

2.9166666666666665


Sqrt() Function : 

In [160]:
#var = np.array([[1,2],[3,4],[5,6]])
np.sqrt(var)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

Std() Function : Menghitung deviasi standar dari array.

In [174]:
np.std(var)

1.707825127659933

# Operations in array (Aritmatika)
Operasi-operasi pada array, terutama dalam konteks numpy, sangat berguna dalam pengolahan data numerik. Berikut ini adalah beberapa operasi umum yang dapat dilakukan pada array:

In [98]:
a = np.array([[7,2],[3,4]])
print(a)

[[7 2]
 [3 4]]


In [97]:
b = np.array([[1,3],[3,7]])
print(b)

[[1 3]
 [3 7]]


penjumlahan :

In [99]:
print(a+b)

[[ 8  5]
 [ 6 11]]


pengurangan : 

In [100]:
print(a-b)

[[ 6 -1]
 [ 0 -3]]


pembagian :

In [101]:
print(a/b)

[[7.         0.66666667]
 [1.         0.57142857]]


perkalian : 

In [102]:
print(a*b)

[[ 7  6]
 [ 9 28]]


# Matrix products dot()
Metode dot() dalam NumPy digunakan untuk melakukan perkalian matriks antara dua array multidimensi. Operasi ini menghasilkan hasil kali dot antara dua matriks.

Berikut ini adalah contoh penggunaan metode dot() untuk melakukan perkalian matriks:

In [132]:
z = np.array([[7,2],[3,4]])
print(z)
x = np.array([[1,3],[3,7]])
print(x)
z.dot(x)

[[7 2]
 [3 4]]
[[1 3]
 [3 7]]


array([[13, 35],
       [15, 37]])

Elemen pada baris pertama, kolom pertama:
7 * 1 + 2 * 3 = 7 + 6 = 13

Elemen pada baris pertama, kolom kedua:
7 * 3 + 2 * 7 = 21 + 14 = 35

Elemen pada baris kedua, kolom pertama:
3 * 1 + 4 * 3 = 3 + 12 = 15

Elemen pada baris kedua, kolom kedua:
3 * 3 + 4 * 7 = 9 + 28 = 37
