In [3]:
import numpy as np

# Iterasi:
NumPy array mendukung iterasi menggunakan loop for atau fungsi numpy.nditer(). Anda dapat mengakses setiap elemen array secara terpisah untuk melakukan operasi yang diperlukan. Contoh:


# 1.Iterasi dengan for loop:
Anda dapat menggunakan for loop untuk mengiterasi melalui elemen-elemen dalam array NumPy. Dalam hal ini, setiap iterasi akan memberikan akses langsung ke elemen-elemen tersebut. Contoh:

In [4]:
arr5 = np.array([10, 20, 30, 40, 50])
for x in arr5:
    print(x)

10
20
30
40
50


In [11]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# Use flatten()

In [14]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


# 2.Iterasi dengan numpy.nditer():
Fungsi numpy.nditer() digunakan untuk melakukan iterasi melalui elemen-elemen dalam array NumPy dengan lebih fleksibel. Dengan numpy.nditer(), Anda dapat mengatur berbagai opsi iterasi, seperti menentukan urutan iterasi, mengatur langkah iterasi, dan mengontrol tipe data elemen yang dikembalikan. Contoh:

In [5]:
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr6):
    print(x)

1
2
3
4
5
6


"F" (Fortran-style):
Ketika Anda menggunakan nilai "F" untuk parameter "order", elemen-elemen dalam array multidimensi diatur secara berurutan dalam memori dalam urutan kolom. Ini berarti elemen-elemen di setiap kolom diikuti oleh elemen-elemen pada kolom berikutnya dalam memori. Contoh:

In [21]:
for x in np.nditer(arr6,order='F'):
    print(x)

1
4
2
5
3
6


supply flags on for loop :

In [20]:
for x in np.nditer(arr6,order='F',flags=['external_loop']):
    print(x)

[1 4]
[2 5]
[3 6]


op_flag on for loop :

In [26]:
for x in np.nditer(arr6,op_flags=['readwrite']):
    x[...]=x*x

In [27]:
arr6

array([[   1,   16,   81],
       [ 256,  625, 1296]])

 iterate two arrays :

In [28]:
arr7 = np.arange(3,15,4).reshape(3,1)
arr7

array([[ 3],
       [ 7],
       [11]])

Untuk mengiterasi dua array secara bersamaan dalam Python, Anda dapat menggunakan fungsi zip(). Fungsi zip() mengambil beberapa objek yang dapat diiterasi sebagai argumen dan mengembalikan iterator berupa tupel-tupel di mana setiap tupel berisi elemen-elemen yang sesuai dari objek-objek masukan.

In [32]:
for x,y in zip(arr6,arr7):
    print(x,y)

[ 1 16 81] [3]
[ 256  625 1296] [7]
